# Generated by Django 3.2.12 on 2022-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_bus', models.TextField(verbose_name='Городские автобусы')),
                ('ap_minsk', models.TextField(verbose_name='Жодино-Минск')),
                ('sovetskaya_minsk', models.TextField(verbose_name='Советская-Минск')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
