# Generated by Django 3.2.12 on 2022-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_schedulebus'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebus',
            name='ap_minsk_weekend',
            field=models.TextField(default=1, verbose_name='Жодино-Минск Вс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulebus',
            name='sovetskaya_minsk_weekend',
            field=models.TextField(default=1, verbose_name='Советская-Минск Сб-Вс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulebus',
            name='ap_minsk',
            field=models.TextField(verbose_name='Жодино-Минск Пн-Сб'),
        ),
        migrations.AlterField(
            model_name='schedulebus',
            name='sovetskaya_minsk',
            field=models.TextField(verbose_name='Советская-Минск Пн-Пт'),
        ),
    ]
