# Generated by Django 3.2.12 on 2022-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20220404_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebus',
            name='title',
            field=models.CharField(default='1', max_length=150),
        ),
    ]
